# Generated by Django 2.1.2 on 2020-05-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200518_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Film'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.UserInformation'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Occupation'),
        ),
    ]
