# Generated by Django 3.0.3 on 2020-05-25 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('anyo', models.IntegerField()),
                ('editor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='film',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rateDate',
        ),
        migrations.AddField(
            model_name='rating',
            name='isbn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
