# Generated by Django 3.0.3 on 2020-05-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200525_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='anyo',
            field=models.CharField(max_length=100),
        ),
    ]
