# Generated by Django 3.0.3 on 2020-05-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200511_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='puntuacion',
            field=models.FloatField(null=True, verbose_name='Puntuacion'),
        ),
    ]
