# Generated by Django 3.0.3 on 2020-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200511_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vino',
            name='uva',
        ),
        migrations.AddField(
            model_name='vino',
            name='uva',
            field=models.ManyToManyField(to='main.Uva'),
        ),
    ]
